#!/usr/bin/env python3
import json
import sys

def dump(obj):
    if obj:
        json.dump(obj, sys.stdout, indent=1, ensure_ascii=False, check_circular=False)
        print()

def format_src(src, cell_type):
    if isinstance(src, list):
        src = "".join(src)
    if cell_type != "code":
        src = "# " + "# ".join(src.splitlines(keepends=True))
    return src

def clean_code_output(cell):
    cell.pop("outputs", None)
    cell.pop("execution_count", None)
    if "metadata" in cell:
        m = cell["metadata"]
        m.pop("collapsed", None)
        m.pop("scrolled", None)


nb = json.load(open(sys.argv[1]))
cells = nb.pop("cells")
dump(nb)

for cell in cells:
    cell_type = cell.pop("cell_type")

    if cell_type == "code":
        clean_code_output(cell)

    if not cell.get("metadata", None):
        # remove empty metadata
        cell.pop("metadata", None)

    src = format_src(cell.pop("source"), cell_type)

    dump(cell)
    print(src, end="\n\n")
